### ISSUE TITLE
TypeError: Cannot read property 'timeout' of undefined

### ISSUE THREAD

**Issue by thearduinoguy** [haf-decent/arpping#2]
Trying to run your test code and I am getting the following errors:

/home/pi/node_modules/arpping/index.js:192
    if (options.timeout) {
                ^

TypeError: Cannot read property 'timeout' of undefined
    at module.exports (/home/pi/node_modules/arpping/index.js:192:17)
    at Object.<anonymous> (/home/pi/wifiscan.js:1:33)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11

**Comment by haf-decent** [comment]
Hey, apologies for not getting back to you sooner. I believe I resolved this issue in a previous update, but I just published v1.0.0 which restructures the whole module, so this is most definitely resolved.
